=== Chocodevit/LMSGI_DTD/joc.dtd
<!ELEMENT joc (titol,companyia,plataforma,part,anyLlançament,personatges)>
<!ELEMENT titol (#PCDATA)>
<!ELEMENT companyia (#PCDATA)>
<!ELEMENT plataforma (#PCDATA)>
<!ELEMENT part (#PCDATA)>
<!ELEMENT anyLlançament (#PCDATA)>
<!ELEMENT personatges (personatge+)>
<!ELEMENT personatge (nom,rol)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT rol (#PCDATA)>

=== Chocodevit/LMSGI_DTD/joc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE joc SYSTEM "joc.dtd">
<joc>
    <titol>Final Fantasy VII</titol>
    <companyia>Square Enix</companyia>
    <plataforma>PlayStation</plataforma>
    <anyLlançament>1997</anyLlançament>
    <personatges>
        <personatge>
            <nom>Cloud Strife</nom>
            <rol>Protagonista</rol>
        </personatge>
        <personatge>
            <nom>Tifa Lockhart</nom>
            <rol>Suport</rol>
        </personatge>
        <personatge>
            <nom>Sephiroth</nom>
            <rol>Antagonista</rol>
        </personatge>
    </personatges>
</joc>
