=== Chocodevit/LMSGI_DTD/joc2/joc.dtd
<!ELEMENT joc (titol,companyia,plataforma,anyLlançament,personatges,nivells)>
<!ELEMENT titol (#PCDATA)>
<!ELEMENT companyia (#PCDATA)>
<!ELEMENT plataforma (#PCDATA)>
<!ELEMENT anyLlançament (#PCDATA)>
<!ELEMENT personatges (personatge+)>
<!ELEMENT personatge (nom)>
<!ATTLIST personatge tipus CDATA #REQUIRED>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT nivells (nivel+)>
<!ELEMENT nivell (nom)>
<!ATTLIST nivell dificultat (baixa | mitjana |alta) #REQUIRED>

=== Chocodevit/LMSGI_DTD/joc2/joc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE joc SYSTEM "joc.dtd">
<joc>
    <titol>Jak and Daxter: The Precursor Legacy</titol>
    <companyia>Naughty Dog</companyia>
    <plataforma>PlayStation 2</plataforma>
    <anyLlançament>2001</anyLlançament>
    <personatges>
        <personatge tipus="heroi">
            <nom>Jak</nom>
        </personatge>
        <personatge tipus="company">
            <nom>Daxter</nom>
        </personatge>
        <personatge tipus="mentora">
            <nom>Samos</nom>
        </personatge>
    </personatges>
    <nivells>
        <nivell dificultat="baixa">
            <nom>Geyser Rock</nom>
        </nivell>
        <nivell dificultat="mitjana">
            <nom>Sandover Village</nom>
        </nivell>
        <nivell dificultat="alta">
            <nom>Gol and Maia's Citadel</nom>
        </nivell>
    </nivells>
</joc>
